proxies:
  - {name: ğŸ‡¯ğŸ‡µH2 æ—¥æœ¬01 JPT, server: jp1.netbridge.uk, port: 10000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: jp1.netbridge.uk, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡¯ğŸ‡µH2 æ—¥æœ¬02  JPT, server: jp1.netbridge.uk, port: 20000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: jp1.netbridge.uk, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡¯ğŸ‡µH2 æ—¥æœ¬03  JPT, server: jp1.netbridge.uk, port: 30000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: jp1.netbridge.uk, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡°ğŸ‡·H2 éŸ©å›½01  KRE, server: korea-01.netbridge.uk, port: 10000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: korea-01.netbridge.uk, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡°ğŸ‡·H2 éŸ©å›½02  KRE, server: korea-01.netbridge.uk, port: 20000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: korea-01.netbridge.uk, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡°ğŸ‡·H2 éŸ©å›½03  KRE, server: korea-01.netbridge.uk, port: 30000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: korea-01.netbridge.uk, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡ºğŸ‡¸H2 ç¾å›½01 CAR, server: usa-j2.netbridge.uk, port: 1000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: usa-j2.netbridge.uk, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡ºğŸ‡¸H2 ç¾å›½02 CAR, server: usa-j2.netbridge.uk, port: 2000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: usa-j2.netbridge.uk, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡ºğŸ‡¸H2 ç¾å›½03 CAR, server: usa-j2.netbridge.uk, port: 3000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: usa-j2.netbridge.uk, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡­ğŸ‡°H2 é¦™æ¸¯01 HKC, server: hk1.netbridge.uk, port: 10000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: hk1.netbridge.uk, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡­ğŸ‡°H2 é¦™æ¸¯02 HKC, server: hk1.netbridge.uk, port: 20000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: hk1.netbridge.uk, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡­ğŸ‡°H2 é¦™æ¸¯03 HKC, server: hk1.netbridge.uk, port: 30000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: hk1.netbridge.uk, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡µğŸ‡­H2 è²å¾‹å®¾01 PHI, server: phi-01.netbridge.uk, port: 1443, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: 192.168.191.224, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡ºğŸ‡¸H2 ç¾å›½01 CLA, server: usa-j1.netbridge.uk, port: 1000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: usa-j1.netbridge.uk, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡ºğŸ‡¸H2 ç¾å›½02 CLA, server: usa-j1.netbridge.uk, port: 2000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: usa-j1.netbridge.uk, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡ºğŸ‡¸H2 ç¾å›½03 CLA, server: usa-j1.netbridge.uk, port: 3000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: usa-j1.netbridge.uk, skip-cert-verify: false, udp: true}
  -
    name: ' ä¿„ç½—æ–¯ B | åº”æ€¥ '
    type: vmess
    server: epgmj.u92.dfnode.top
    port: 30002
    uuid: 466622a0-f2cd-3375-854b-1c4ef5993ccb
    alterId: 0
    cipher: auto
    udp: true
    servername: download.windowsupdate.com
  -
    name: 'ä¿„ç½—æ–¯ A | ä½é€Ÿ'
    type: vmess
    server: ducsh.downca.potatoeswater.com
    port: 30002
    uuid: 466622a0-f2cd-3375-854b-1c4ef5993ccb
    alterId: 0
    cipher: auto
    udp: true
    servername: download.windowsupdate.com
  -
    name: 'æ¾³å¤§åˆ©äºš A | é«˜é€Ÿ '
    type: vmess
    server: jaxld.downca.potatoeswater.com
    port: 39310
    uuid: 466622a0-f2cd-3375-854b-1c4ef5993ccb
    alterId: 0
    cipher: auto
    udp: true
    servername: download.windowsupdate.com
