proxies:
    - 
    name: 'ç¾å›½ A54 | æ—¥å¸¸ é«˜é€Ÿ ä¸­å»¶è¿Ÿ'
    type: vmess
    server: onmkx.jd.alphagatelink.com
    port: 30004
    uuid: 863bef10-f254-3581-a7a6-ad067cc4232a
    alterId: 0
    cipher: auto
    udp: true
    servername: download.windowsupdate.com
    - 
    name: 'ç¾å›½ B54 | æ—¥å¸¸ é«˜é€Ÿ ä¸­å»¶è¿Ÿ'
    type: vmess
    server: tcpik.baidu.alphagatelink.com
    port: 30004
    uuid: 863bef10-f254-3581-a7a6-ad067cc4232a
    alterId: 0
    cipher: auto
    udp: true
    servername: download.windowsupdate.com
    - 
    name: 'ç¾å›½ çº½çº¦ B31 | å®˜ç½‘dfhl1.com'
    type: vmess
    server: emhab.bilibili.exn21ba-c4sja3-4324-abc-oline.com
    port: 15732
    uuid: 863bef10-f254-3581-a7a6-ad067cc4232a
    alterId: 0
    cipher: auto
    udp: true
    servername: download.windowsupdate.com
    - 
    name: 'æ–°åŠ å¡ A32 | æ—¥å¸¸ ä¸­é€Ÿ'
    type: vmess
    server: chqmt.weixin.exn21ba-c4sja3-4324-abc-oline.com
    port: 15736
    uuid: 863bef10-f254-3581-a7a6-ad067cc4232a
    alterId: 0
    cipher: auto
    udp: true
    servername: download.windowsupdate.com
    - 
    name: 'ä¿„ç½—æ–¯ A31 | æ—¥å¸¸ ä½é€Ÿ ç›—ç‰ˆç«™'
    type: vmess
    server: qchwv.weibo.exn21ba-c4sja3-4324-abc-oline.com
    port: 30002
    uuid: 863bef10-f254-3581-a7a6-ad067cc4232a
    alterId: 0
    cipher: auto
    udp: true
    servername: download.windowsupdate.com
    - 
    name: 'æ–°åŠ å¡ B32 | æ—¥å¸¸ ä¸­é€Ÿ'
    type: vmess
    server: nuybd.douyin.alphagatelink.com
    port: 15736
    uuid: 863bef10-f254-3581-a7a6-ad067cc4232a
    alterId: 0
    cipher: auto
    udp: true
    servername: download.windowsupdate.com
    - 
    name: 'ç¾å›½ çº½çº¦ A31 | å®˜ç½‘d03.in'
    type: vmess
    server: gajnh.downca.potatoeswater.com
    port: 15732
    uuid: 863bef10-f254-3581-a7a6-ad067cc4232a
    alterId: 0
    cipher: auto
    udp: true
    servername: download.windowsupdate.com
    - 
    name: ' ä¿„ç½—æ–¯ B21 | åº”æ€¥ ä½é€Ÿ ç›—ç‰ˆç«™'
    type: vmess
    server: eqcab.360.alphagatelink.com
    port: 30002
    uuid: 863bef10-f254-3581-a7a6-ad067cc4232a
    alterId: 0
    cipher: auto
    udp: true
    servername: download.windowsupdate.com
    - 
    name: 'ç‘å…¸ A91 | åŒ—æ¬§'
    type: vmess
    server: conyd.weibo.exn21ba-c4sja3-4324-abc-oline.com
    port: 19351
    uuid: 863bef10-f254-3581-a7a6-ad067cc4232a
    alterId: 0
    cipher: auto
    udp: true
    servername: download.windowsupdate.com
    
    - { name: 'ğŸ‡­ğŸ‡° HK ', type: ss, server: 51fan.stardad.lol, port: 34929, cipher: chacha20-ietf-poly1305, password: ecb55a5c-18af-4063-9fe3-20b32d3ef2e4, udp: true }
    - { name: 'ğŸ‡­ğŸ‡° HK ', type: ss, server: 51fan.stardad.lol, port: 42675, cipher: chacha20-ietf-poly1305, password: ecb55a5c-18af-4063-9fe3-20b32d3ef2e4, udp: true }
    - { name: 'ğŸ‡­ğŸ‡° HK ', type: ss, server: 51fan.stardad.lol, port: 33313, cipher: chacha20-ietf-poly1305, password: ecb55a5c-18af-4063-9fe3-20b32d3ef2e4, udp: true }
    - { name: 'ğŸ‡­ğŸ‡° HK  home', type: ss, server: 51fan.stardad.lol, port: 26733, cipher: chacha20-ietf-poly1305, password: ecb55a5c-18af-4063-9fe3-20b32d3ef2e4, udp: true }
    - { name: 'ğŸ‡­ğŸ‡° HK  home', type: ss, server: 51fan.stardad.lol, port: 13213, cipher: chacha20-ietf-poly1305, password: ecb55a5c-18af-4063-9fe3-20b32d3ef2e4, udp: true }
    - { name: 'ğŸ‡¯ğŸ‡µ JP ', type: ss, server: 51fan.stardad.lol, port: 26905, cipher: chacha20-ietf-poly1305, password: ecb55a5c-18af-4063-9fe3-20b32d3ef2e4, udp: true }
    - { name: 'ğŸ‡¯ğŸ‡µ JP ', type: ss, server: 51fan.stardad.lol, port: 43712, cipher: chacha20-ietf-poly1305, password: ecb55a5c-18af-4063-9fe3-20b32d3ef2e4, udp: true }
    - { name: 'ğŸ‡¹ğŸ‡¼ TW  home', type: ss, server: 51fan.stardad.lol, port: 49171, cipher: chacha20-ietf-poly1305, password: ecb55a5c-18af-4063-9fe3-20b32d3ef2e4, udp: true }
    - { name: 'ğŸ‡¸ğŸ‡¬ SG ', type: ss, server: 51fan.stardad.lol, port: 16845, cipher: chacha20-ietf-poly1305, password: ecb55a5c-18af-4063-9fe3-20b32d3ef2e4, udp: true }
    - { name: 'ğŸ‡ºğŸ‡¸ US ', type: ss, server: 51fan.stardad.lol, port: 50943, cipher: chacha20-ietf-poly1305, password: ecb55a5c-18af-4063-9fe3-20b32d3ef2e4, udp: true }
    - { name: 'ğŸ‡ºğŸ‡¸ US ', type: ss, server: 51fan.stardad.lol, port: 23537, cipher: chacha20-ietf-poly1305, password: ecb55a5c-18af-4063-9fe3-20b32d3ef2e4, udp: true }
    - { name: 'ğŸ‡ºğŸ‡¸ us ', type: ss, server: 51fan.stardad.lol, port: 23751, cipher: chacha20-ietf-poly1305, password: ecb55a5c-18af-4063-9fe3-20b32d3ef2e4, udp: true }
    - { name: 'ğŸ‡§ğŸ‡· BR ', type: ss, server: 51fan.stardad.lol, port: 36584, cipher: chacha20-ietf-poly1305, password: ecb55a5c-18af-4063-9fe3-20b32d3ef2e4, udp: true }
