proxies:
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯ 00
    type: ss
    server: hk00.ofopp.com
    port: 32566
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯ 01
    type: ss
    server: hk01.ofopp.com
    port: 10001
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯ 02
    type: ss
    server: hk02.ofopp.com
    port: 10002
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯ 03
    type: ss
    server: hk03.ofopp.com
    port: 10003
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯ 04
    type: ss
    server: hk04.ofopp.com
    port: 10004
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯ 05
    type: ss
    server: hk05.ofopp.com
    port: 10005
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯ 06
    type: ss
    server: hk06.ofopp.com
    port: 10006
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯ 07
    type: ss
    server: hk07.ofopp.com
    port: 10007
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯ 08
    type: ss
    server: hk08.ofopp.com
    port: 10008
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡¨ğŸ‡³ å°æ¹¾ 00
    type: ss
    server: tw00.ofopp.com
    port: 14000
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡¨ğŸ‡³ å°æ¹¾ 01
    type: ss
    server: tw01.ofopp.com
    port: 14001
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡¨ğŸ‡³ å°æ¹¾ 02
    type: ss
    server: tw02.ofopp.com
    port: 14002
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡¨ğŸ‡³ å°æ¹¾ 03
    type: ss
    server: tw03.ofopp.com
    port: 14003
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡¨ğŸ‡³ å°æ¹¾ 04
    type: ss
    server: tw04.ofopp.com
    port: 14004
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ 00
    type: ss
    server: sg00.ofopp.com
    port: 12000
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ 01
    type: ss
    server: sg01.ofopp.com
    port: 12001
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ 02
    type: ss
    server: sg02.ofopp.com
    port: 12002
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ 03
    type: ss
    server: sg03.ofopp.com
    port: 12003
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ 04
    type: ss
    server: sg04.ofopp.com
    port: 12004
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ 05
    type: ss
    server: sg05.ofopp.com
    port: 12005
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 02
    type: ss
    server: jp02.ofopp.com
    port: 11002
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 03
    type: ss
    server: jp03.ofopp.com
    port: 11003
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 04
    type: ss
    server: jp04.ofopp.com
    port: 11004
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 05
    type: ss
    server: jp05.ofopp.com
    port: 11005
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 06
    type: ss
    server: jp06.ofopp.com
    port: 11006
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡ºğŸ‡¸ ç¾å›½ 00
    type: ss
    server: us00.ofopp.com
    port: 13000
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡ºğŸ‡¸ ç¾å›½ 01
    type: ss
    server: us01.ofopp.com
    port: 13001
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡ºğŸ‡¸ ç¾å›½ 02
    type: ss
    server: us02.ofopp.com
    port: 13002
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡ºğŸ‡¸ ç¾å›½ 03
    type: ss
    server: us03.ofopp.com
    port: 13003
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡ºğŸ‡¸ ç¾å›½ 04
    type: ss
    server: us04.ofopp.com
    port: 13004
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡ºğŸ‡¸ ç¾å›½ 05
    type: ss
    server: us05.ofopp.com
    port: 13005
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡ºğŸ‡¸ ç¾å›½ 06
    type: ss
    server: us06.ofopp.com
    port: 13006
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡°ğŸ‡· éŸ©å›½ 01
    type: ss
    server: kr01.ofopp.com
    port: 25001
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡°ğŸ‡· éŸ©å›½ 02
    type: ss
    server: kr01.ofopp.com
    port: 25002
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡µğŸ‡­ è²å¾‹å®¾ 01
    type: ss
    server: ph01.ofopp.com
    port: 20001
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡²ğŸ‡¾ é©¬æ¥è¥¿äºš 01
    type: ss
    server: my01.ofopp.com
    port: 16001
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡²ğŸ‡¾ é©¬æ¥è¥¿äºš 02
    type: ss
    server: my02.ofopp.com
    port: 16002
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡¨ğŸ‡¦ åŠ æ‹¿å¤§ 01
    type: ss
    server: ca01.ofopp.com
    port: 18001
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡¨ğŸ‡¦ åŠ æ‹¿å¤§ 02
    type: ss
    server: ca02.ofopp.com
    port: 18002
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡®ğŸ‡³ å°åº¦ 01
    type: ss
    server: in01.ofopp.com
    port: 26001
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡®ğŸ‡³ å°åº¦ 02
    type: ss
    server: in02.ofopp.com
    port: 26002
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡§ğŸ‡· å·´è¥¿ 01
    type: ss
    server: br01.ofopp.com
    port: 27001
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡¹ğŸ‡· åœŸè€³å…¶ 01
    type: ss
    server: tr01.ofopp.com
    port: 19001
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡¹ğŸ‡­ æ³°å›½ 01
    type: ss
    server: th01.ofopp.com
    port: 24001
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡»ğŸ‡³ è¶Šå— 01
    type: ss
    server: vn01.ofopp.com
    port: 21001
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡·ğŸ‡º ä¿„ç½—æ–¯ 01
    type: ss
    server: ru01.ofopp.com
    port: 22001
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡¦ğŸ‡· é˜¿æ ¹å»· 01
    type: ss
    server: ar01.ofopp.com
    port: 22001
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡¬ğŸ‡§ è‹±å›½ 01
    type: ss
    server: gb01.ofopp.com
    port: 15001
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡¬ğŸ‡§ è‹±å›½ 02
    type: ss
    server: gb02.ofopp.com
    port: 15002
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
  - name: ğŸ‡©ğŸ‡ª å¾·å›½ 01
    type: ss
    server: de01.ofopp.com
    port: 17001
    cipher: aes-256-gcm
    password: 76f00418-2d5b-4dc2-8181-fe5f04af4cc1
    udp: true
