proxies:
  - { name: 'ğŸ‡¸ğŸ‡¬æ–°åŠ å¡ 1x', type: ss, server: ni8.gy2.xn--rcyy4g.com, port: 42729, cipher: chacha20-ietf-poly1305, password: 6cc54963-8471-46cf-8c56-dfabcbd251b1, udp: true }
  - { name: 'ğŸ‡¯ğŸ‡µæ—¥æœ¬åŸç”Ÿ 1x', type: ss, server: ni8.gy5.wenrouyun.cn, port: 52530, cipher: chacha20-ietf-poly1305, password: 6cc54963-8471-46cf-8c56-dfabcbd251b1, udp: true }
  - { name: 'ğŸ‡¯ğŸ‡µæ—¥æœ¬ 1x', type: ss, server: ni8.gy2.xn--rcyy4g.com, port: 22225, cipher: chacha20-ietf-poly1305, password: 6cc54963-8471-46cf-8c56-dfabcbd251b1, udp: true }
  - { name: 'ğŸ‡­ğŸ‡°é¦™æ¸¯ 1x', type: ss, server: ni8.gy2.xn--rcyy4g.com, port: 39210, cipher: chacha20-ietf-poly1305, password: 6cc54963-8471-46cf-8c56-dfabcbd251b1, udp: true }
  - { name: 'ğŸ‡­ğŸ‡°é¦™æ¸¯2-åŸç”Ÿ 1x', type: ss, server: ni8.gy5.wenrouyun.cn, port: 38896, cipher: chacha20-ietf-poly1305, password: 6cc54963-8471-46cf-8c56-dfabcbd251b1, udp: true }
  - { name: 'ğŸ‡ºğŸ‡¸ç¾å›½ 1x', type: ss, server: ni8.gy2.xn--rcyy4g.com, port: 40824, cipher: chacha20-ietf-poly1305, password: 6cc54963-8471-46cf-8c56-dfabcbd251b1, udp: true }
  - { name: 'ğŸ‡ºğŸ‡¸ç¾å›½2 1x', type: ss, server: 1.gy.xn--rcyy4g.com, port: 32262, cipher: chacha20-ietf-poly1305, password: 6cc54963-8471-46cf-8c56-dfabcbd251b1, udp: true }
  - { name: 'ğŸ‡¨ğŸ‡¦åŠ æ‹¿å¤§ 1x', type: ss, server: ni8.gy2.xn--rcyy4g.com, port: 16943, cipher: chacha20-ietf-poly1305, password: 6cc54963-8471-46cf-8c56-dfabcbd251b1, udp: true }
  - { name: 'ğŸ‡©ğŸ‡ªå¾·å›½ 1x', type: ss, server: ni8.gy5.wenrouyun.cn, port: 15092, cipher: chacha20-ietf-poly1305, password: 6cc54963-8471-46cf-8c56-dfabcbd251b1, udp: true }
  - { name: 'ğŸ‡°ğŸ‡·éŸ©å›½ 2x', type: ss, server: ni8.gy5.wenrouyun.cn, port: 29082, cipher: chacha20-ietf-poly1305, password: 6cc54963-8471-46cf-8c56-dfabcbd251b1, udp: true }
  - { name: 'ğŸ‡ªğŸ‡¸è¥¿ç­ç‰™ 1x', type: ss, server: 1.gy.xn--rcyy4g.com, port: 23731, cipher: chacha20-ietf-poly1305, password: 6cc54963-8471-46cf-8c56-dfabcbd251b1, udp: true }
  - { name: å¤‡ç”¨, type: ss, server: cloudgd.coemn.com, port: 21878, cipher: chacha20-ietf-poly1305, password: 6cc54963-8471-46cf-8c56-dfabcbd251b1, udp: true }
  - { name: 'ğŸ‡¦ğŸ‡ªè¿ªæ‹œ 1x', type: ss, server: 1.gy.xn--rcyy4g.com, port: 15701, cipher: chacha20-ietf-poly1305, password: 6cc54963-8471-46cf-8c56-dfabcbd251b1, udp: true }
  - { name: æ—¥æœ¬-ç›´è¿, type: ss, server: cmi.jp1.ty7.fun, port: 2345, cipher: chacha20-ietf-poly1305, password: 6cc54963-8471-46cf-8c56-dfabcbd251b1, udp: true }
  - {name: ğŸ‡¯ğŸ‡µH2 æ—¥æœ¬01 JPT, server: jp1.netbridge.uk, port: 10000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: jp1.netbridge.uk, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡¯ğŸ‡µH2 æ—¥æœ¬02  JPT, server: jp1.netbridge.uk, port: 20000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: jp1.netbridge.uk, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡¯ğŸ‡µH2 æ—¥æœ¬03  JPT, server: jp1.netbridge.uk, port: 30000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: jp1.netbridge.uk, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡°ğŸ‡·H2 éŸ©å›½01  KRE, server: korea-01.netbridge.uk, port: 10000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: korea-01.netbridge.uk, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡°ğŸ‡·H2 éŸ©å›½02  KRE, server: korea-01.netbridge.uk, port: 20000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: korea-01.netbridge.uk, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡°ğŸ‡·H2 éŸ©å›½03  KRE, server: korea-01.netbridge.uk, port: 30000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: korea-01.netbridge.uk, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡ºğŸ‡¸H2 ç¾å›½01 CAR, server: usa-j2.netbridge.uk, port: 1000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: usa-j2.netbridge.uk, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡ºğŸ‡¸H2 ç¾å›½02 CAR, server: usa-j2.netbridge.uk, port: 2000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: usa-j2.netbridge.uk, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡ºğŸ‡¸H2 ç¾å›½03 CAR, server: usa-j2.netbridge.uk, port: 3000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: usa-j2.netbridge.uk, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡­ğŸ‡°H2 é¦™æ¸¯01 HKC, server: hk1.netbridge.uk, port: 10000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: hk1.netbridge.uk, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡­ğŸ‡°H2 é¦™æ¸¯02 HKC, server: hk1.netbridge.uk, port: 20000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: hk1.netbridge.uk, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡­ğŸ‡°H2 é¦™æ¸¯03 HKC, server: hk1.netbridge.uk, port: 30000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: hk1.netbridge.uk, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡µğŸ‡­H2 è²å¾‹å®¾01 PHI, server: phi-01.netbridge.uk, port: 1443, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: 192.168.191.224, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡ºğŸ‡¸H2 ç¾å›½01 CLA, server: usa-j1.netbridge.uk, port: 1000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: usa-j1.netbridge.uk, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡ºğŸ‡¸H2 ç¾å›½02 CLA, server: usa-j1.netbridge.uk, port: 2000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: usa-j1.netbridge.uk, skip-cert-verify: false, udp: true}
  - {name: ğŸ‡ºğŸ‡¸H2 ç¾å›½03 CLA, server: usa-j1.netbridge.uk, port: 3000, client-fingerprint: chrome, type: hysteria2, password: e367d55f-25a2-4e54-aef2-676f13735a6c, sni: usa-j1.netbridge.uk, skip-cert-verify: false, udp: true}
  -
    name: ' ä¿„ç½—æ–¯ B | åº”æ€¥ '
    type: vmess
    server: epgmj.u92.dfnode.top
    port: 30002
    uuid: 466622a0-f2cd-3375-854b-1c4ef5993ccb
    alterId: 0
    cipher: auto
    udp: true
    servername: download.windowsupdate.com
  -
    name: 'ä¿„ç½—æ–¯ A | ä½é€Ÿ'
    type: vmess
    server: ducsh.downca.potatoeswater.com
    port: 30002
    uuid: 466622a0-f2cd-3375-854b-1c4ef5993ccb
    alterId: 0
    cipher: auto
    udp: true
    servername: download.windowsupdate.com
  -
    name: 'æ¾³å¤§åˆ©äºš A | é«˜é€Ÿ '
    type: vmess
    server: jaxld.downca.potatoeswater.com
    port: 39310
    uuid: 466622a0-f2cd-3375-854b-1c4ef5993ccb
    alterId: 0
    cipher: auto
    udp: true
    servername: download.windowsupdate.com
  -
    name: 'å°æ¹¾ A91 | æ—¥å¸¸ é«˜é€Ÿ æµåª’ä½“ ChatGPT'
    type: vmess
    server: nbyqf.downca.potatoeswater.com
    port: 39260
    uuid: 466622a0-f2cd-3375-854b-1c4ef5993ccb
    alterId: 0
    cipher: auto
    udp: true
    servername: download.windowsupdate.com
  -
    name: 'å°æ¹¾ B91 | æ—¥å¸¸ é«˜é€Ÿ æµåª’ä½“ ChatGPT'
    type: vmess
    server: wixyl.u92.dfnode.top
    port: 39260
    uuid: 466622a0-f2cd-3375-854b-1c4ef5993ccb
    alterId: 0
    cipher: auto
    udp: true
    servername: download.windowsupdate.com
  -
    name: 'æ³•å›½ A92 | å¥¥è¿ç‰¹ä¾› æ—¥å¸¸ é«˜é€Ÿ'
    type: vmess
    server: ahrog.downca.potatoeswater.com
    port: 39270
    uuid: 466622a0-f2cd-3375-854b-1c4ef5993ccb
    alterId: 0
    cipher: auto
    udp: true
    servername: download.windowsupdate.com
  -
    name: 'è¶Šå— B91 | ç‰¹æ®Š é«˜é€Ÿ æµåª’ä½“'
    type: vmess
    server: ropqu.u92.dfnode.top
    port: 19366
    uuid: 466622a0-f2cd-3375-854b-1c4ef5993ccb
    alterId: 0
    cipher: auto
    udp: true
    servername: download.windowsupdate.com
  -
    name: 'æ—¥æœ¬ A91 | æ—¥å¸¸ é«˜é€Ÿ æµåª’ä½“'
    type: vmess
    server: cmrvl.downca.potatoeswater.com
    port: 39262
    uuid: 466622a0-f2cd-3375-854b-1c4ef5993ccb
    alterId: 0
    cipher: auto
    udp: true
    servername: download.windowsupdate.com
  -
    name: 'æ—¥æœ¬ B91 | æ—¥å¸¸ é«˜é€Ÿ æµåª’ä½“'
    type: vmess
    server: dpwtg.u92.dfnode.top
    port: 19262
    uuid: 466622a0-f2cd-3375-854b-1c4ef5993ccb
    alterId: 0
    cipher: auto
    udp: true
    servername: download.windowsupdate.com
