proxies:
  - { name: 'ğŸ‡§ğŸ‡· BR 1-1', type: ss, server: 51fan.stardad.lol, port: 36584, cipher: chacha20-ietf-poly1305, password: ecb55a5c-18af-4063-9fe3-20b32d3ef2e4, udp: true }
  - { name: 'ğŸ‡©ğŸ‡ª DE 2-1', server: de.taipeicity.news, port: 60898, sni: 'https://bing.com', up: 10, down: 10, skip-cert-verify: true, type: hysteria2, password: c64c5250-e20d-48d2-a3d2-d2794442ffd8 }
  - { name: 'ğŸ‡¯ğŸ‡µ JP 3-1', server: jpzl2.stardad.lol, port: 48512, sni: 'https://bing.com', up: 10, down: 10, skip-cert-verify: true, type: hysteria2, password: c64c5250-e20d-48d2-a3d2-d2794442ffd8 }
  - { name: 'ğŸ‡¸ğŸ‡¬ SG 2-1', server: sgzl2.stardad.lol, port: 35701, sni: 'https://bing.com', up: 10, down: 10, skip-cert-verify: true, type: hysteria2, password: c64c5250-e20d-48d2-a3d2-d2794442ffd8 }
  - { name: 'ğŸ‡»ğŸ‡³ VN 2-1', server: vn.taipeicity.news, port: 23656, sni: 'https://bing.com', up: 10, down: 10, skip-cert-verify: true, type: hysteria2, password: c64c5250-e20d-48d2-a3d2-d2794442ffd8 }
  - name: HKé¦™æ¸¯-01
    type: ss
    server: fdydgz.nekors.3406xyz.xyz
    port: 35967
    cipher: chacha20-ietf-poly1305
    password: 9f7d6b69-a771-4843-a3c1-7f5ce75f2e24
    udp: true
  - name: HKé¦™æ¸¯-02
    type: ss
    server: fdyd500nn.nekros.3406xyz.xyz
    port: 59447
    cipher: chacha20-ietf-poly1305
    password: 9f7d6b69-a771-4843-a3c1-7f5ce75f2e24
    udp: true
  - name: HKé¦™æ¸¯-03
    type: ss
    server: fdydgz.nekors.3406xyz.xyz
    port: 54589
    cipher: chacha20-ietf-poly1305
    password: 9f7d6b69-a771-4843-a3c1-7f5ce75f2e24
    udp: true
  - name: HKé¦™æ¸¯-04
    type: ss
    server: fdyd500nn.nekros.3406xyz.xyz
    port: 51741
    cipher: chacha20-ietf-poly1305
    password: 9f7d6b69-a771-4843-a3c1-7f5ce75f2e24
    udp: true
  - name: USç¾å›½-01
    type: ss
    server: fdydgz.nekors.3406xyz.xyz
    port: 44706
    cipher: chacha20-ietf-poly1305
    password: 9f7d6b69-a771-4843-a3c1-7f5ce75f2e24
    udp: true
  - name: USç¾å›½-02
    type: ss
    server: fdyd500nn.nekros.3406xyz.xyz
    port: 30625
    cipher: chacha20-ietf-poly1305
    password: 9f7d6b69-a771-4843-a3c1-7f5ce75f2e24
    udp: true
  - name: USç¾å›½-03
    type: ss
    server: fdydgz.nekors.3406xyz.xyz
    port: 14733
    cipher: chacha20-ietf-poly1305
    password: 9f7d6b69-a771-4843-a3c1-7f5ce75f2e24
    udp: true
  - name: USç¾å›½-04
    type: ss
    server: fdyd500nn.nekros.3406xyz.xyz
    port: 42597
    cipher: chacha20-ietf-poly1305
    password: 9f7d6b69-a771-4843-a3c1-7f5ce75f2e24
    udp: true
  - name: JPæ—¥æœ¬-01
    type: ss
    server: fdydgz.nekors.3406xyz.xyz
    port: 31791
    cipher: chacha20-ietf-poly1305
    password: 9f7d6b69-a771-4843-a3c1-7f5ce75f2e24
    udp: true
  - name: JPæ—¥æœ¬-02
    type: ss
    server: fdyd500nn.nekros.3406xyz.xyz
    port: 29092
    cipher: chacha20-ietf-poly1305
    password: 9f7d6b69-a771-4843-a3c1-7f5ce75f2e24
    udp: true
  - name: JPæ—¥æœ¬-03
    type: ss
    server: fdydgz.nekors.3406xyz.xyz
    port: 59085
    cipher: chacha20-ietf-poly1305
    password: 9f7d6b69-a771-4843-a3c1-7f5ce75f2e24
    udp: true
  - name: JPæ—¥æœ¬-04
    type: ss
    server: fdyd500nn.nekros.3406xyz.xyz
    port: 28818
    cipher: chacha20-ietf-poly1305
    password: 9f7d6b69-a771-4843-a3c1-7f5ce75f2e24
    udp: true
  - name: SGæ–°åŠ å¡-01
    type: ss
    server: fdydgz.nekors.3406xyz.xyz
    port: 14679
    cipher: chacha20-ietf-poly1305
    password: 9f7d6b69-a771-4843-a3c1-7f5ce75f2e24
    udp: true
  - name: SGæ–°åŠ å¡-02
    type: ss
    server: fdyd500nn.nekros.3406xyz.xyz
    port: 23133
    cipher: chacha20-ietf-poly1305
    password: 9f7d6b69-a771-4843-a3c1-7f5ce75f2e24
    udp: true
  - name: SGæ–°åŠ å¡-03
    type: ss
    server: fdydgz.nekors.3406xyz.xyz
    port: 27106
    cipher: chacha20-ietf-poly1305
    password: 9f7d6b69-a771-4843-a3c1-7f5ce75f2e24
    udp: true
  - name: SGæ–°åŠ å¡-04
    type: ss
    server: fdyd500nn.nekros.3406xyz.xyz
    port: 14646
    cipher: chacha20-ietf-poly1305
    password: 9f7d6b69-a771-4843-a3c1-7f5ce75f2e24
    udp: true
  - name: DEå¾·å›½-ä½å®…
    type: ss
    server: fdydgz.nekors.3406xyz.xyz
    port: 20743
    cipher: aes-128-gcm
    password: 9f7d6b69-a771-4843-a3c1-7f5ce75f2e24
    udp: true
  - name: HLè·å…°
    type: ss
    server: fdydgz.nekors.3406xyz.xyz
    port: 19201
    cipher: chacha20-ietf-poly1305
    password: 9f7d6b69-a771-4843-a3c1-7f5ce75f2e24
    udp: true
  - name: ISå†°å²›
    type: ss
    server: fdydgz.nekors.3406xyz.xyz
    port: 55372
    cipher: aes-128-gcm
    password: 9f7d6b69-a771-4843-a3c1-7f5ce75f2e24
    udp: true
  - name: FRæ³•å›½
    type: ss
    server: fdydgz.nekors.3406xyz.xyz
    port: 51715
    cipher: chacha20-ietf-poly1305
    password: 9f7d6b69-a771-4843-a3c1-7f5ce75f2e24
    udp: true
  - name: ITæ„å¤§åˆ©
    type: ss
    server: fdydgz.nekors.3406xyz.xyz
    port: 41412
    cipher: aes-128-gcm
    password: 9f7d6b69-a771-4843-a3c1-7f5ce75f2e24
    udp: true
