proxies:
- { name: 'ğŸ‡­ğŸ‡° HK 1', type: ss, server: 51fan.stardad.lol, port: 34929, cipher: chacha20-ietf-poly1305, password: ecb55a5c-18af-4063-9fe3-20b32d3ef2e4, udp: true }
- { name: 'ğŸ‡­ğŸ‡° HK 2', type: ss, server: 51fan.stardad.lol, port: 42675, cipher: chacha20-ietf-poly1305, password: ecb55a5c-18af-4063-9fe3-20b32d3ef2e4, udp: true }
- { name: 'ğŸ‡­ğŸ‡° HK 3', type: ss, server: 51fan.stardad.lol, port: 33313, cipher: chacha20-ietf-poly1305, password: ecb55a5c-18af-4063-9fe3-20b32d3ef2e4, udp: true }
- { name: 'ğŸ‡­ğŸ‡° HK  home 1', type: ss, server: 51fan.stardad.lol, port: 26733, cipher: chacha20-ietf-poly1305, password: ecb55a5c-18af-4063-9fe3-20b32d3ef2e4, udp: true }
- { name: 'ğŸ‡­ğŸ‡° HK  home 2', type: ss, server: 51fan.stardad.lol, port: 13213, cipher: chacha20-ietf-poly1305, password: ecb55a5c-18af-4063-9fe3-20b32d3ef2e4, udp: true }
- { name: 'ğŸ‡¯ğŸ‡µ JP 1', type: ss, server: 51fan.stardad.lol, port: 26905, cipher: chacha20-ietf-poly1305, password: ecb55a5c-18af-4063-9fe3-20b32d3ef2e4, udp: true }
- { name: 'ğŸ‡¯ğŸ‡µ JP 2', type: ss, server: 51fan.stardad.lol, port: 43712, cipher: chacha20-ietf-poly1305, password: ecb55a5c-18af-4063-9fe3-20b32d3ef2e4, udp: true }
- { name: 'ğŸ‡¹ğŸ‡¼ TW  home 1', type: ss, server: 51fan.stardad.lol, port: 49171, cipher: chacha20-ietf-poly1305, password: ecb55a5c-18af-4063-9fe3-20b32d3ef2e4, udp: true }
- { name: 'ğŸ‡¸ğŸ‡¬ SG 1', type: ss, server: 51fan.stardad.lol, port: 16845, cipher: chacha20-ietf-poly1305, password: ecb55a5c-18af-4063-9fe3-20b32d3ef2e4, udp: true }
- { name: 'ğŸ‡ºğŸ‡¸ US 1', type: ss, server: 51fan.stardad.lol, port: 50943, cipher: chacha20-ietf-poly1305, password: ecb55a5c-18af-4063-9fe3-20b32d3ef2e4, udp: true }
- { name: 'ğŸ‡ºğŸ‡¸ US 2', type: ss, server: 51fan.stardad.lol, port: 23537, cipher: chacha20-ietf-poly1305, password: ecb55a5c-18af-4063-9fe3-20b32d3ef2e4, udp: true }
- { name: 'ğŸ‡ºğŸ‡¸ us 3', type: ss, server: 51fan.stardad.lol, port: 23751, cipher: chacha20-ietf-poly1305, password: ecb55a5c-18af-4063-9fe3-20b32d3ef2e4, udp: true }
- { name: 'ğŸ‡§ğŸ‡· BR 1', type: ss, server: 51fan.stardad.lol, port: 36584, cipher: chacha20-ietf-poly1305, password: ecb55a5c-18af-4063-9fe3-20b32d3ef2e4, udp: true }
- { name: 'ğŸ‡©ğŸ‡ª DE 2', server: de.taipeicity.news, port: 60898, sni: 'https://bing.com', up: 10, down: 10, skip-cert-verify: true, type: hysteria2, password: c64c5250-e20d-48d2-a3d2-d2794442ffd8 }
- { name: 'ğŸ‡¯ğŸ‡µ JP 3', server: jpzl2.stardad.lol, port: 48512, sni: 'https://bing.com', up: 10, down: 10, skip-cert-verify: true, type: hysteria2, password: c64c5250-e20d-48d2-a3d2-d2794442ffd8 }
- { name: 'ğŸ‡¸ğŸ‡¬ SG 2', server: sgzl2.stardad.lol, port: 35701, sni: 'https://bing.com', up: 10, down: 10, skip-cert-verify: true, type: hysteria2, password: c64c5250-e20d-48d2-a3d2-d2794442ffd8 }
- { name: 'ğŸ‡»ğŸ‡³ VN 2', server: vn.taipeicity.news, port: 23656, sni: 'https://bing.com', up: 10, down: 10, skip-cert-verify: true, type: hysteria2, password: c64c5250-e20d-48d2-a3d2-d2794442ffd8 }
- 
  name: 'ç¾å›½ | æ—¥å¸¸ é«˜é€Ÿ ä¸­å»¶è¿Ÿ'
  type: vmess
  server: onmkx.jd.alphagatelink.com
  port: 30004
  uuid: 863bef10-f254-3581-a7a6-ad067cc4232a
  alterId: 0
  cipher: auto
  udp: true
  servername: download.windowsupdate.com
- 
  name: 'ç¾å›½  | æ—¥å¸¸ é«˜é€Ÿ ä¸­å»¶è¿Ÿ'
  type: vmess
  server: tcpik.baidu.alphagatelink.com
  port: 30004
  uuid: 863bef10-f254-3581-a7a6-ad067cc4232a
  alterId: 0
  cipher: auto
  udp: true
  servername: download.windowsupdate.com
- 
  name: 'ç¾å›½ çº½çº¦ | å®˜ç½‘dfhl1.com'
  type: vmess
  server: emhab.bilibili.exn21ba-c4sja3-4324-abc-oline.com
  port: 15732
  uuid: 863bef10-f254-3581-a7a6-ad067cc4232a
  alterId: 0
  cipher: auto
  udp: true
  servername: download.windowsupdate.com
- 
  name: 'æ–°åŠ å¡  1| æ—¥å¸¸ ä¸­é€Ÿ'
  type: vmess
  server: chqmt.weixin.exn21ba-c4sja3-4324-abc-oline.com
  port: 15736
  uuid: 863bef10-f254-3581-a7a6-ad067cc4232a
  alterId: 0
  cipher: auto
  udp: true
  servername: download.windowsupdate.com
- 
  name: 'ä¿„ç½—æ–¯  1| æ—¥å¸¸ ä½é€Ÿ ç›—ç‰ˆç«™'
  type: vmess
  server: qchwv.weibo.exn21ba-c4sja3-4324-abc-oline.com
  port: 30002
  uuid: 863bef10-f254-3581-a7a6-ad067cc4232a
  alterId: 0
  cipher: auto
  udp: true
  servername: download.windowsupdate.com
- 
  name: 'æ–°åŠ å¡  2| æ—¥å¸¸ ä¸­é€Ÿ'
  type: vmess
  server: nuybd.douyin.alphagatelink.com
  port: 15736
  uuid: 863bef10-f254-3581-a7a6-ad067cc4232a
  alterId: 0
  cipher: auto
  udp: true
  servername: download.windowsupdate.com
- 
  name: 'ç¾å›½ çº½çº¦ A'
  type: vmess
  server: gajnh.downca.potatoeswater.com
  port: 15732
  uuid: 863bef10-f254-3581-a7a6-ad067cc4232a
  alterId: 0
  cipher: auto
  udp: true
  servername: download.windowsupdate.com
- 
  name: ' ä¿„ç½—æ–¯ B| åº”æ€¥ ä½é€Ÿ ç›—ç‰ˆç«™'
  type: vmess
  server: eqcab.360.alphagatelink.com
  port: 30002
  uuid: 863bef10-f254-3581-a7a6-ad067cc4232a
  alterId: 0
  cipher: auto
  udp: true
  servername: download.windowsupdate.com
- 
  name: 'ç‘å…¸ A| åŒ—æ¬§'
  type: vmess
  server: conyd.weibo.exn21ba-c4sja3-4324-abc-oline.com
  port: 19351
  uuid: 863bef10-f254-3581-a7a6-ad067cc4232a
  alterId: 0
  cipher: auto
  udp: true
  servername: download.windowsupdate.com
